/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         document_id: "document_id"
 *     }
 */
export interface GetRequest {
    /**
     * The unique identifier of the document to get
     */
    document_id: string;
}
