/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         index_name: undefined,
 *         document_id: "document_id",
 *         context: "context",
 *         content: "content"
 *     }
 */
export interface IndexRequest {
    /** The name of the index to which the document will be added */
    index_name?: string;
    /** A unique identifier for the document */
    document_id: string;
    /** The context of the document that will be indexed */
    context: string;
    /** The content of the document that will be returned in the tool response */
    content: string;
}
