/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         document_id: "document_id",
 *         is_active: true,
 *         context: ["context", "context"],
 *         content: "content"
 *     }
 */
export interface UpdateRequest {
    /**
     * The unique identifier of the document to update
     */
    document_id: string;
    /**
     * Whether the document is active
     */
    is_active: boolean;
    /**
     * The context of the document, as a list of strings, that will be indexed.
     */
    context: string[];
    /**
     * The content of the document that will be returned in the tool response. If not provided, the document will be removed from the index.
     */
    content: string;
}
