/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernFai from "../../index.js";

/**
 * @example
 *     {}
 */
export interface GetConversationsRequest {
    /**
     * The type of conversation to retrieve
     */
    source?: FernFai.ConversationSource;
    /**
     * The page number to retrieve
     */
    page?: number;
    /**
     * The number of conversations to retrieve per page
     */
    limit?: number;
}
