/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Analytics", () => {
    test("getHistogramAnalytics", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bars: [
                { label: "label", conversationCount: 1 },
                { label: "label", conversationCount: 1 },
            ],
        };
        server
            .mockEndpoint()
            .get("/analytics/histogram/domain")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.analytics.getHistogramAnalytics("domain", {
            start_date: "start_date",
            end_date: "end_date",
            groupBy: "DAY",
        });
        expect(response).toEqual({
            bars: [
                {
                    label: "label",
                    conversationCount: 1,
                },
                {
                    label: "label",
                    conversationCount: 1,
                },
            ],
        });
    });
});
