/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Chat", () => {
    test("chatCompletion", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: undefined,
            system_prompt: undefined,
            messages: [
                { role: "role", text: "text" },
                { role: "role", text: "text" },
            ],
        };
        const rawResponseBody = { turn: { role: "role", text: "text" } };
        server
            .mockEndpoint()
            .post("/chat/domain")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.chat.chatCompletion("domain", {
            model: undefined,
            system_prompt: undefined,
            messages: [
                {
                    role: "role",
                    text: "text",
                },
                {
                    role: "role",
                    text: "text",
                },
            ],
        });
        expect(response).toEqual({
            turn: {
                role: "role",
                text: "text",
            },
        });
    });
});
