/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool.js";
import { FernFaiClient } from "../../src/Client";

describe("Index", () => {
    test("indexDocument", async () => {
        const server = mockServerPool.createServer();
        const client = new FernFaiClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            index_name: undefined,
            document_id: "document_id",
            context: "context",
            content: "content",
        };

        server.mockEndpoint().post("/index/domain").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.index.indexDocument("domain", {
            index_name: undefined,
            document_id: "document_id",
            context: "context",
            content: "content",
        });
        expect(response).toEqual(undefined);
    });
});
