version: "3.9"

services:
  db:
    image: postgres:15
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fai:
    build: .
    container_name: fai-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PYTHONPATH=${PYTHONPATH}:${PWD}
      - POSTGRES_DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/mydatabase
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TURBOPUFFER_API_KEY=${TURBOPUFFER_API_KEY}
    volumes:
      - .:/app

volumes:
  pgdata:
