/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernFai from "../../../../index.js";

/**
 * @example
 *     {
 *         model: undefined,
 *         system_prompt: undefined,
 *         messages: [{
 *                 role: "role",
 *                 text: "text"
 *             }, {
 *                 role: "role",
 *                 text: "text"
 *             }]
 *     }
 */
export interface ChatCompletionRequest {
    model?: string;
    system_prompt?: string;
    messages: FernFai.ChatTurn[];
}
