/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConversationSource = "CHAT" | "MCP";
export const ConversationSource = {
    Chat: "CHAT",
    Mcp: "MCP",
} as const;
