/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ContextResponse {
    document_id: string;
    domain: string;
    context_id: string;
    context: string[];
    content: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
}
